USE trialmatch_db;

DELIMITER //

CREATE TRIGGER trg_prevent_invalid_patient_age_insert
BEFORE INSERT ON patient_profiles
FOR EACH ROW
BEGIN
  IF NEW.age < 0 OR NEW.age > 120 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'Invalid patient age. Age must be between 0 and 120.';
  END IF;
END//

CREATE TRIGGER trg_set_criteria_metrics_insert
BEFORE INSERT ON eligibility_criteria
FOR EACH ROW
BEGIN
  SET NEW.text_length = CHAR_LENGTH(NEW.criteria_text);

  IF NEW.complexity_score IS NULL OR NEW.complexity_score = 0 THEN
    SET NEW.complexity_score = LEAST(99.99, CHAR_LENGTH(NEW.criteria_text) / 20);
  END IF;
END//

CREATE TRIGGER trg_audit_trial_insert
AFTER INSERT ON trials
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (table_name, record_pk, action_type, new_values)
  VALUES (
    'trials',
    NEW.trial_id,
    'INSERT',
    JSON_OBJECT('nct_id', NEW.nct_id, 'brief_title', NEW.brief_title)
  );
END//

CREATE TRIGGER trg_update_match_status_insert
BEFORE INSERT ON patient_trial_matches
FOR EACH ROW
BEGIN
  IF NEW.match_score >= 75 AND NEW.criteria_review_required = FALSE AND NEW.structured_match_passed = TRUE THEN
    SET NEW.match_status = 'Potential Match';
  ELSEIF NEW.match_score >= 40 OR NEW.criteria_review_required = TRUE THEN
    SET NEW.match_status = 'Needs Review';
  ELSE
    SET NEW.match_status = 'Not Suitable';
  END IF;
END//

CREATE TRIGGER trg_match_status_history_after_insert
AFTER INSERT ON patient_trial_matches
FOR EACH ROW
BEGIN
  INSERT INTO match_status_history (match_id, old_status, new_status, change_reason)
  VALUES (NEW.match_id, NULL, NEW.match_status, 'Initial match status generated by trigger.');
END//

DELIMITER ;