USE trialmatch_db;

-- ============================================================
-- Triggers
-- These demonstrate database-side integrity, automatic metric
-- calculation, status rules, audit logging, and status history.
-- Application code still validates inputs, but these rules protect
-- the database if data is inserted or updated outside the API.
-- ============================================================

DELIMITER //

CREATE TRIGGER trg_prevent_invalid_patient_age_insert
BEFORE INSERT ON patient_profiles
FOR EACH ROW
BEGIN
  IF NEW.age < 0 OR NEW.age > 120 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'Invalid patient age. Age must be between 0 and 120.';
  END IF;
END//

CREATE TRIGGER trg_prevent_invalid_patient_age_update
BEFORE UPDATE ON patient_profiles
FOR EACH ROW
BEGIN
  IF NEW.age < 0 OR NEW.age > 120 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'Invalid patient age. Age must be between 0 and 120.';
  END IF;
END//

CREATE TRIGGER trg_set_criteria_metrics_insert
BEFORE INSERT ON eligibility_criteria
FOR EACH ROW
BEGIN
  SET NEW.text_length = CHAR_LENGTH(NEW.criteria_text);

  IF NEW.complexity_score IS NULL OR NEW.complexity_score = 0 THEN
    SET NEW.complexity_score = LEAST(99.99, CHAR_LENGTH(NEW.criteria_text) / 20);
  END IF;
END//

CREATE TRIGGER trg_set_criteria_metrics_update
BEFORE UPDATE ON eligibility_criteria
FOR EACH ROW
BEGIN
  SET NEW.text_length = CHAR_LENGTH(NEW.criteria_text);

  IF NEW.complexity_score IS NULL OR NEW.complexity_score = 0 THEN
    SET NEW.complexity_score = LEAST(99.99, CHAR_LENGTH(NEW.criteria_text) / 20);
  END IF;
END//

CREATE TRIGGER trg_audit_trial_insert
AFTER INSERT ON trials
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (user_id, table_name, record_pk, action_type, new_values)
  VALUES (
    NULLIF(@app_user_id, 0),
    'trials',
    NEW.trial_id,
    'INSERT',
    JSON_OBJECT(
      'nct_id', NEW.nct_id,
      'brief_title', NEW.brief_title,
      'phase_id', NEW.phase_id,
      'status_id', NEW.status_id,
      'study_type_id', NEW.study_type_id,
      'sex_id', NEW.sex_id,
      'minimum_age', NEW.minimum_age,
      'maximum_age', NEW.maximum_age,
      'healthy_volunteers', NEW.healthy_volunteers,
      'is_archived', NEW.is_archived
    )
  );
END//

CREATE TRIGGER trg_audit_trial_update
AFTER UPDATE ON trials
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (user_id, table_name, record_pk, action_type, old_values, new_values)
  VALUES (
    NULLIF(@app_user_id, 0),
    'trials',
    NEW.trial_id,
    CASE
      WHEN OLD.is_archived = FALSE AND NEW.is_archived = TRUE THEN 'ARCHIVE'
      ELSE 'UPDATE'
    END,
    JSON_OBJECT(
      'brief_title', OLD.brief_title,
      'phase_id', OLD.phase_id,
      'status_id', OLD.status_id,
      'study_type_id', OLD.study_type_id,
      'sex_id', OLD.sex_id,
      'minimum_age', OLD.minimum_age,
      'maximum_age', OLD.maximum_age,
      'healthy_volunteers', OLD.healthy_volunteers,
      'is_archived', OLD.is_archived
    ),
    JSON_OBJECT(
      'brief_title', NEW.brief_title,
      'phase_id', NEW.phase_id,
      'status_id', NEW.status_id,
      'study_type_id', NEW.study_type_id,
      'sex_id', NEW.sex_id,
      'minimum_age', NEW.minimum_age,
      'maximum_age', NEW.maximum_age,
      'healthy_volunteers', NEW.healthy_volunteers,
      'is_archived', NEW.is_archived
    )
  );
END//

CREATE TRIGGER trg_update_match_status_insert
BEFORE INSERT ON patient_trial_matches
FOR EACH ROW
BEGIN
  IF NEW.match_score >= 75 AND NEW.criteria_review_required = FALSE AND NEW.structured_match_passed = TRUE THEN
    SET NEW.match_status = 'Potential Match';
  ELSEIF NEW.match_score >= 40 OR NEW.criteria_review_required = TRUE THEN
    SET NEW.match_status = 'Needs Review';
  ELSE
    SET NEW.match_status = 'Not Suitable';
  END IF;
END//

CREATE TRIGGER trg_update_match_status_update
BEFORE UPDATE ON patient_trial_matches
FOR EACH ROW
BEGIN
  IF NEW.match_score >= 75 AND NEW.criteria_review_required = FALSE AND NEW.structured_match_passed = TRUE THEN
    SET NEW.match_status = 'Potential Match';
  ELSEIF NEW.match_score >= 40 OR NEW.criteria_review_required = TRUE THEN
    SET NEW.match_status = 'Needs Review';
  ELSE
    SET NEW.match_status = 'Not Suitable';
  END IF;
END//

CREATE TRIGGER trg_match_status_history_after_insert
AFTER INSERT ON patient_trial_matches
FOR EACH ROW
BEGIN
  INSERT INTO match_status_history (match_id, old_status, new_status, change_reason)
  VALUES (NEW.match_id, NULL, NEW.match_status, 'Initial match status generated by trigger.');
END//

CREATE TRIGGER trg_match_status_history_after_update
AFTER UPDATE ON patient_trial_matches
FOR EACH ROW
BEGIN
  IF NOT (OLD.match_status <=> NEW.match_status) THEN
    INSERT INTO match_status_history (match_id, old_status, new_status, change_reason)
    VALUES (NEW.match_id, OLD.match_status, NEW.match_status, 'Match status recalculated after update.');
  END IF;
END//

DELIMITER ;
